### ISSUE TITLE
Request: Compatibility with Tidy5e Sheet

### ISSUE THREAD

**Issue by bearsy1** [krbz999/addar#2]
Could we hope to see this module work with Tidy5e Sheet in the (near) future? As is with the default sheet, this module works just fine though!

**Comment by krbz999** [comment]
Have the Tidy dev make a PR, if necessary. I don't use the module so it's easier for them to do it or provide whatever html tags needed on their sheet.

**Comment by bearsy1** [comment]
Roger that!
